# Generated by Django 5.1 on 2024-08-19 14:40

import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userdetails_about_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Enter a valid email'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[user.validators.UserDetailsValidator.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(max_length=255, validators=[user.validators.UserDetailsValidator.validate_name]),
        ),
    ]
