# Generated by Django 5.1 on 2024-08-19 16:01

import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userdetails_email_alter_userdetails_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.CharField(max_length=255, unique=True, validators=[user.validators.UserDetailsValidator.validate_email]),
        ),
    ]
