# Generated by Django 5.1 on 2024-08-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
