# Generated by Django 5.1 on 2024-08-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userdetails_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
