# Generated by Django 5.1 on 2024-08-21 12:09

import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userdetails_address_alter_userdetails_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(max_length=255, validators=[user.validators.UserDetailsValidator.validate_password]),
        ),
    ]
