# Generated by Django 5.1 on 2024-08-24 06:03

import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_userdetails_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_number',
            field=models.IntegerField(max_length=10, validators=[user.validators.UserDetailsValidator.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='responsibilities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
