# Generated by Django 5.1 on 2024-08-24 06:03

import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userdetails_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_number',
            field=models.IntegerField(validators=[user.validators.UserDetailsValidator.validate_phone_number]),
        ),
    ]
