# Generated by Django 5.1 on 2024-08-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_userdetails_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='to',
            field=models.DateField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='worked_from',
            field=models.DateField(blank=True, default='None', null=True),
        ),
    ]
