# Generated by Django 5.1 on 2024-08-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_userdetails_to_alter_userdetails_worked_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='to',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='worked_from',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
