# Generated by Django 5.1 on 2024-08-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('experience', models.CharField(max_length=255)),
                ('work_location', models.CharField(max_length=255)),
                ('employment_type', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('about_company', models.TextField()),
                ('website', models.URLField()),
                ('openings', models.IntegerField()),
                ('no_of_applicants', models.IntegerField(default=0)),
                ('application_deadline', models.DateField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='user.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_email', models.CharField(max_length=255)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdetails')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='job.jobdetails')),
            ],
        ),
    ]
